# Problem Statement 1: 

Write a function so that the columns of the output matrix are powers of the input 	 vector. 
 
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 
  
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde. 


Solution without using inbuilt vander function:-

In [1]:
import numpy as np

In [2]:
def vander_matrix(vector, N, increasing=False):
    
    if not increasing:
        matrix = np.column_stack([vector**(N-1-i) for i in range(N)])
    elif increasing:
        matrix = np.column_stack([vector**i for i in range(N)])
    
    return matrix


In [12]:
print("OUTPUT:-\n")

vector = np.array([1,2,3,4,5])
N = 3
output_matrix_inc_false = vander_matrix(vector,N,False)
output_matrix_inc_true = vander_matrix(vector,N,True)

print("The input vector: ",vector)
print("\nNumber of columns in output matrix should be: ",N)
print("\nVander matrix of the input array when increasing False:\n\n",output_matrix_inc_false)
print("\nVander matrix of the input array when increasing True:\n\n",output_matrix_inc_true)

vector_demo1 = np.array([1,2,4,6,8,10])
N = 5
output_matrix_inc_false = vander_matrix(vector_demo1,N,False)
output_matrix_inc_true = vander_matrix(vector_demo1,N,True)

print("The input vector: ",vector_demo1)
print("\nNumber of columns in output matrix should be: ",N)
print("\nVander matrix of the input array when increasing False:\n",output_matrix_inc_false)
print("\nVander matrix of the input array when increasing True:\n",output_matrix_inc_true)


OUTPUT:-

The input vector:  [1 2 3 4 5]

Number of columns in output matrix should be:  3

Vander matrix of the input array when increasing False:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]

Vander matrix of the input array when increasing True:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
The input vector:  [ 1  2  4  6  8 10]

Number of columns in output matrix should be:  5

Vander matrix of the input array when increasing False:
 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]]

Vander matrix of the input array when increasing True:
 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]]


Solution using inbuilt function:-

In [6]:
np.vander([1,2,3,4,5],3,increasing=True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])

In [7]:
np.vander([1,2,4,6,8,10],5) # By default increasing will be False

array([[    1,     1,     1,     1,     1],
       [   16,     8,     4,     2,     1],
       [  256,    64,    16,     4,     1],
       [ 1296,   216,    36,     6,     1],
       [ 4096,   512,    64,     8,     1],
       [10000,  1000,   100,    10,     1]])

# Problem Statement 2: 

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: 
 
The moving average sequence has n-k+1 elements as shown below. 
 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
 
 i 1  2  3  4  5  6  7  8  9 10  ===== == == == == == == == == == == 
Input 10 20 30 40 50 60 70 80 90 100   	y1      25 = (10+20+30+40)/4  	y2      35 = (20+30+40+50)/4  	y3      45 = (30+40+50+60)/4 
y4 	55 = (40+50+60+70)/4 
y5 	65 = (50+60+70+80)/4 
y6 	75 = (60+70+80+90)/4 
y7 	85 = (70+80+90+100)/4 
 
 
Thus, the moving average sequence has n-k+1=10-4+1=7 values. 
Question: Write a function to find moving average in an array over a window: 
         Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 


In [35]:
##Moving average
def moving_avg(l, N):
    result = []
    for i in range(0, len(l)-N+1):
        output = np.sum(l[i:i+N])/N
        result.append(output)
    return np.array(result)

In [36]:
l = np.array([10,20,30,40,50,60,70,80,90,100])
N = 3
print(moving_avg(l,N))

[20. 30. 40. 50. 60. 70. 80. 90.]


Question: Write a function to find moving average in an array over a window: 
         Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 


In [37]:
l1 = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
N=4
print(moving_avg(l1,N))

[  4.25   5.5    6.75   7.75  23.5   39.5   57.25  79.25  88.   107.5 ]
